---
kind: pipeline
type: docker
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: staticcheck
  pull: always
  image: golang:1.19
  commands:
  - go get honnef.co/go/tools/cmd/staticcheck
  - go run honnef.co/go/tools/cmd/staticcheck ./...
  volumes:
  - name: gopath
    path: /go

- name: lint
  pull: always
  image: golang:1.19
  commands:
  - go get golang.org/x/lint/golint
  - go run golang.org/x/lint/golint -set_exit_status ./...
  volumes:
  - name: gopath
    path: /go

- name: vet
  pull: always
  image: golang:1.19
  commands:
  - go vet ./...
  volumes:
  - name: gopath
    path: /go

- name: test
  pull: always
  image: golang:1.19
  commands:
  - go test -cover -v ./...
  volumes:
  - name: gopath
    path: /go

volumes:
- name: gopath
  temp: {}

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

...
